### ISSUE TITLE
Support Creating Mock Group without Devices

### ISSUE THREAD

**Issue by brettf** [awslabs/aws-greengrass-group-setup#13]
It would be great if gg_group_setup could support `create-core` followed immediately by `create-group`. At this point in time there's an assumption in the code that there will always be devices created before a `create-group` is called. Came from conversation with: @neelmitra

**Comment by brettf** [comment]
At this point in time if one tries to create-group with a `mock` type without calling `create-devices` first the following error occurs:

````
2018-07-03 16:17:18,073|root    |INFO: CoreDefinitionId: acb87a26-0a19-4091-9f63-d1e5f4912cfa
Traceback (most recent call last):
  File "/usr/local/bin/gg_group_setup", line 11, in <module>
    load_entry_point('gg-group-setup==0.5.2', 'console_scripts', 'gg_group_setup')()
  File "/usr/local/lib/python2.7/site-packages/gg_group_setup/cmd.py", line 847, in main
    fire.Fire(gc)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gg_group_setup/cmd.py", line 74, in create
    group_name=group_name, region=region
  File "/usr/local/lib/python2.7/site-packages/gg_group_setup/cmd.py", line 136, in create_group
    config=config, group_name=group_name
  File "/usr/local/lib/python2.7/site-packages/gg_group_setup/cmd.py", line 191, in _create_device_definition
    device_def = group_type.get_device_definition(config=config)
  File "/usr/local/lib/python2.7/site-packages/gg_group_setup/mock_group.py", line 35, in get_device_definition
    "ThingArn": config['devices']['GGD_example']['thing_arn'],
KeyError: 'GGD_example'
````
